name: Reusable Deploy Workflow

on:
  workflow_call:
    inputs:
      kube-context:
        required: true
        type: string
      docker-image:
        required: true
        type: string
      docker-tag:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubectl context
        run: kubectl config use-context ${{ inputs.kube-context }}

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/myapp myapp=${{ inputs.docker-image }}:${{ inputs.docker-tag }} -n production
          kubectl rollout status deployment/myapp -n production
